DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers (
 id INT NOT NULL AUTO_INCREMENT,
 Burger_name VARCHAR(255) NOT NULL,
 Devoured BOOLEAN DEFAULT FALSE,
 PRIMARY KEY (id)
);